const fs = require('fs');


function createFile() {
  return new Promise((resolve, reject) => {
    const content = 'Hello';
    let file = fs.createWriteStream('file.txt');
    file.on('finish', (e) => {
      resolve();
    });
    file.end(content, () => {
      reject();
    });
  });
}

Promise.resolve(createFile())
.then(function () {
    console.log('Hello from main thread');
  })
.catch(function (error) {
    console.warn('Caught exception from child thread');
    console.warn(String(error));
    process.exit(1);
  });
